window.THEME_GALLERY = [
  {
    "id": "advocacy-network",
    "display_name": "線性網絡節點風",
    "background_color": "#F8F9F7",
    "background_style": "清爽淺底搭配網絡節點、role chip 與 trust / outreach cue，適合 advocacy、ambassador 與 community ops 類內容",
    "primary": "#243344",
    "primary_use": "主標、主要結構、核心 program 脈絡",
    "secondary": "#6C7787",
    "secondary_use": "補充文字、說明與次要 metadata",
    "accent": "#D66A3D",
    "accent_use": "advocacy cue、activation、community momentum",
    "support_hexes": [
      "#E6EDF6",
      "#EDE1D6"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，穩定而具推進感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 role、cadence、support note、impact signal）",
    "illustration_default": "線條圖示",
    "mood": [
      "連結感",
      "線性節點",
      "角色標記",
      "持續節奏"
    ],
    "deco_names": [
      "network-line",
      "role-chip",
      "trust-marker",
      "momentum-arrow"
    ],
    "closing": "The slide should feel like a structured network diagram with visible rhythm: light nodes, connector paths, and role chips should create movement while staying c",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/advocacy-network-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：線性網絡節點風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "advocacy-network",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/advocacy-network.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "blueprint-radial",
    "display_name": "深藍製圖放射風",
    "background_color": "#07263D",
    "background_style": "深藍製圖底搭配細緻格線、放射構造線與低密度校準記號，整體精確、空間化且安靜未來",
    "primary": "#E9FCFF",
    "primary_use": "主標、主要文字與最高層級線條",
    "secondary": "#8FE6F3",
    "secondary_use": "格線、次要文字、構造線與線框物件",
    "accent": "#FFB24A",
    "accent_use": "單一校準點、短刻度與有限重點",
    "support_hexes": [
      "#174865",
      "#07263D"
    ],
    "typography_heading": "IBM Plex Mono / Noto Sans Mono bold/700（取角色範圍上緣，保持明確的等寬節奏）",
    "typography_body": "IBM Plex Mono / Noto Sans Mono regular/400（取角色範圍下緣，適合短標籤與技術性說明）",
    "illustration_default": "線框幾何",
    "mood": [
      "精確",
      "空間感",
      "製圖線框",
      "安靜未來"
    ],
    "deco_names": [
      "drafting-grid",
      "radial-wireframe",
      "calibration-mark",
      "construction-circle"
    ],
    "closing": "Create clarity through drafting geometry, monospaced type, and disciplined asymmetry. Keep every line and marker abstract, reusable, and independent from layout",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme"
  },
  {
    "id": "boardroom-premium",
    "display_name": "暖灰高級指標風",
    "background_color": "#F5F3EF",
    "background_style": "乾淨暖灰底，搭配深石板藍與低飽和金屬色，呈現穩健、成熟、可被信任的 boardroom 氣質",
    "primary": "#1F2733",
    "primary_use": "主標、核心數字、主結構線與決策欄位",
    "secondary": "#707887",
    "secondary_use": "次要敘述、caption、說明文字與輔助標籤",
    "accent": "#B5873E",
    "accent_use": "重點標記、decision cue、關鍵訊號與判斷焦點",
    "support_hexes": [
      "#DDE2E8",
      "#D7E3DA"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段偏上，穩重成熟，克制不張揚）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 metric、risk、priority 與 board note）",
    "illustration_default": "無",
    "mood": [
      "穩健",
      "高可信度",
      "暖灰層次",
      "高級節制"
    ],
    "deco_names": [
      "thesis-divider",
      "metric-band",
      "decision-rail",
      "runway-chip"
    ],
    "closing": "The slide should feel premium but restrained: warm-gray fields, measured spacing, and precise metric bands should create a calm, high-confidence information sur",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/boardroom-premium-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：暖灰高級指標風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "boardroom-premium",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/boardroom-premium.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "brand-activation",
    "display_name": "亮橘緞帶圖框風",
    "background_color": "#FBFAF7",
    "background_style": "乾淨亮色底，搭配鮮明重點色與高可視模組，適合外向、高辨識的視覺節奏",
    "primary": "#22324A",
    "primary_use": "主標、主體結構、關鍵文字",
    "secondary": "#6E7482",
    "secondary_use": "補充說明、caption、次要文案",
    "accent": "#E36B2C",
    "accent_use": "CTA、亮點統計、重點標記",
    "support_hexes": [
      "#D9E5F2",
      "#F3DFC9"
    ],
    "typography_heading": "Noto Sans TC bold/700–800（取角色範圍中段偏上，具展示感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，乾淨俐落）",
    "illustration_default": "扁平插畫",
    "mood": [
      "外向",
      "清楚",
      "高彩對比",
      "緞帶圖框"
    ],
    "deco_names": [
      "cta-ribbon",
      "gallery-frame",
      "channel-pill"
    ],
    "closing": "The slide should feel polished, energetic, and easy to scan. Orange ribbon accents, bright framing, and clean white space should carry the visual identity witho",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/brand-activation-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：亮橘緞帶圖框風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "brand-activation",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/brand-activation.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "brand-editorial",
    "display_name": "金褐出版排版風",
    "background_color": "#1A1A1A",
    "background_style": "雙模式背景——深灰黑色版本（#1A1A1A）為主調，搭配白色/淺灰版本； 攝影背景時疊加半透明色塊提高可讀性\n",
    "primary": "#D4AF7E",
    "primary_use": "裝飾線條、標籤背景、強調條帶（品牌簽名色）",
    "secondary": "#4A8B8B",
    "secondary_use": "重點標籤、內容框、按鈕",
    "accent": "#FF6633",
    "accent_use": "數字編號、強調文字",
    "support_hexes": [],
    "typography_heading": "思源黑體（Noto Sans TC） bold/700–900（取角色範圍上緣，大標可佔頁面上方三分之一，白色（深背景）或黑色（淺背景））",
    "typography_body": "Noto Serif TC 或 Noto Sans TC regular/400–500（取角色範圍下緣，點列組織為主，深灰或白色）",
    "illustration_default": "無",
    "mood": [
      "專業沉穩",
      "金褐色帶",
      "出版排版",
      "品牌感強"
    ],
    "deco_names": [
      "diagonal-slash",
      "dot-pattern",
      "horizontal-strip",
      "polaroid-frame",
      "badge-label",
      "underline-accent",
      "translucent-overlay",
      "rounded-content-card"
    ],
    "closing": "Gold-brown (#D4AF7E) is the signature decorative color for lines, labels, and accent strips. Alternate light and dark grounds to create rhythm; keep the aesthet",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/brand-editorial-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：金褐出版排版風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "brand-editorial",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/brand-editorial.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "brutal-grunge",
    "display_name": "暗色粗獷框景風",
    "background_color": "#2E2A2A",
    "background_style": "深石墨灰底，帶刮痕、磨損、暗霧質感",
    "primary": "#F2ECE5",
    "primary_use": "標題與主文字",
    "secondary": "#9C9186",
    "secondary_use": "次要文字、框線",
    "accent": "#FFFFFF",
    "accent_use": "細節星點、強調輪廓",
    "support_hexes": [],
    "typography_heading": "Noto Serif TC（高對比襯線） black/900（取角色範圍上緣，拉高封面氣勢）",
    "typography_body": "窄體無襯線（Noto Sans TC 窄字距） light–regular/300–400（取角色範圍下緣，營造暗色框景張力）",
    "illustration_default": "無",
    "mood": [
      "粗獷",
      "攝影感",
      "暗色戲劇性",
      "磨損質地"
    ],
    "deco_names": [
      "distressed-frame",
      "monochrome-photo",
      "spark-mark"
    ],
    "closing": "The page should feel tactile and dramatic: restrained monochrome tones, strong framing, distressed edges, and dark texture should define the style.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/brutal-grunge-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：暗色粗獷框景風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "brutal-grunge",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/brutal-grunge.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "clean-tech-business",
    "display_name": "白底科技線稿風",
    "background_color": "#FFFFFF",
    "background_style": "白底、深藍黑文字、扁平科技插圖",
    "primary": "#1F2B37",
    "primary_use": "主標與正文",
    "secondary": "#5C7086",
    "secondary_use": "次要說明、圖例與細線",
    "accent": "#8DA8B9",
    "accent_use": "科技插圖、線性點綴、章節號",
    "support_hexes": [
      "#D7E3EA"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，乾淨俐落）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合條列與摘要）",
    "illustration_default": "扁平插畫",
    "mood": [
      "科技感",
      "白底乾淨",
      "線稿插圖",
      "低對比面板"
    ],
    "deco_names": [
      "gear-node",
      "pale-panel",
      "light-outline"
    ],
    "closing": "Keep the visual language modern, clean, and explanatory. Pale panels, thin outlines, and simple line illustrations should clarify structure rather than decorate",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/clean-tech-business-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：白底科技線稿風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "clean-tech-business",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/clean-tech-business.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "clinical-report",
    "display_name": "藍灰幾何切角風",
    "background_color": "#FBFCFD",
    "background_style": "白底或極淺灰底，搭配藍灰幾何切角與細線",
    "primary": "#27343B",
    "primary_use": "標題與正文",
    "secondary": "#7A8FA3",
    "secondary_use": "次標、圖例、輔助線",
    "accent": "#A9C0CF",
    "accent_use": "幾何區塊、章節標示",
    "support_hexes": [
      "#D7E3EA"
    ],
    "typography_heading": "Noto Sans TC（或人文襯線 Noto Serif TC） medium–bold/500–700（取角色範圍中段，簡潔穩定）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，報告型字級節奏，適合摘要與結論）",
    "illustration_default": "線條圖示",
    "mood": [
      "正式",
      "冷靜",
      "藍灰幾何",
      "精準留白"
    ],
    "deco_names": [
      "geometric-cut",
      "thin-network",
      "chapter-number-box"
    ],
    "closing": "The slide should feel trustworthy and precise: clean white space, blue-gray structure, geometric cuts, and thin rules should create an orderly reading pace.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/clinical-report-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：藍灰幾何切角風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "clinical-report",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/clinical-report.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "community-fundraising",
    "display_name": "暖米綠弧線風",
    "background_color": "#FAF7F1",
    "background_style": "溫暖米白或淺奶油底，搭配深藍綠與柔和磚紅，呈現社群可信度、公益感與成員導向的清楚秩序",
    "primary": "#24404A",
    "primary_use": "主標、治理模組、重要結構線與關鍵摘要",
    "secondary": "#6C7784",
    "secondary_use": "說明文字、caption、成員資訊與次要敘述",
    "accent": "#C86F4A",
    "accent_use": "donate cue、highlight statistic、warm CTA 與 participation signal",
    "support_hexes": [
      "#DDE9E4",
      "#F2DFC8"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，溫暖但穩定）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，清晰友善、可長時間閱讀）",
    "illustration_default": "扁平插畫",
    "mood": [
      "溫暖",
      "值得信任",
      "米色底",
      "柔和弧線"
    ],
    "deco_names": [
      "assembly-divider",
      "community-chip",
      "giving-curve",
      "event-pin"
    ],
    "closing": "The slide should feel warm, trustworthy, and structured: cream surfaces, deep green lines, soft coral highlights, and gentle curves should create a human visual",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/community-fundraising-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：暖米綠弧線風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "community-fundraising",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/community-fundraising.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "corporate-blue",
    "display_name": "藍色菱形矩陣風",
    "background_color": "#FFFFFF",
    "background_style": "象牙白或淺灰藍為主背景，搭配深藍幾何色塊作為視覺重心區",
    "primary": "#1E5FBD",
    "primary_use": "標題背景框、重點文字、幾何色塊（主導元素）",
    "secondary": "#4A8FD9",
    "secondary_use": "幾何裝飾塊、漸層背景、副標題強調",
    "accent": "#D85A5A",
    "accent_use": "數據強調、統計圖對比色、重要詞彙標記",
    "support_hexes": [
      "#50C878"
    ],
    "typography_heading": "Microsoft YaHei（或同級無襯線） heavy/900（取角色範圍上緣，極易掃讀，深黑或白色依背景）",
    "typography_body": "Microsoft YaHei（或同級無襯線） regular–medium/400–500（取角色範圍中段，寬鬆行距，深灰至黑色；藍色「»」列表引導符）",
    "illustration_default": "扁平插畫",
    "mood": [
      "專業可信",
      "藍色幾何",
      "菱形矩陣",
      "清晰有序"
    ],
    "deco_names": [
      "diamond-dot-matrix",
      "rotated-square-blocks",
      "gradient-color-block",
      "blue-capsule-label",
      "horizontal-divider",
      "dashed-outline-rect",
      "thick-black-outline",
      "vertical-left-bar"
    ],
    "closing": "Deep blue anchors the structure. Diamond dot matrices and rotated square blocks should mark corners and edges, creating a clean white canvas with disciplined ge",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/corporate-blue-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：藍色菱形矩陣風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "corporate-blue",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/corporate-blue.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "customer-lifecycle",
    "display_name": "藍綠帶狀路徑風",
    "background_color": "#F7F8F6",
    "background_style": "清爽亮底搭配生命周期節奏帶、健康訊號與續約導向標記，適合 onboarding 到 renewal 的連續敘事",
    "primary": "#22303B",
    "primary_use": "主標、主要文字、核心 lifecycle 線索",
    "secondary": "#6B7786",
    "secondary_use": "補充說明、輔助標示、次要 metadata",
    "accent": "#3D8B6D",
    "accent_use": "adoption progress、success cue、renewal confidence",
    "support_hexes": [
      "#DDEAE4",
      "#F0D8C8"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，穩定而友善）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 lifecycle note、health summary、action labels）",
    "illustration_default": "線條圖示",
    "mood": [
      "協作感",
      "持續節奏",
      "藍綠帶狀",
      "路徑導向"
    ],
    "deco_names": [
      "lifecycle-band",
      "success-signal",
      "risk-gap-flag",
      "renewal-timeline"
    ],
    "closing": "The slide should feel like a clear path system: lifecycle bands, progress signals, and gap markers should guide the eye across modules without relying on domain",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/customer-lifecycle-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：藍綠帶狀路徑風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "customer-lifecycle",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/customer-lifecycle.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "dark-circuit",
    "display_name": "暗黑電路板風",
    "background_color": "#1A1A2A",
    "background_style": "深黑色背景，全頁鋪滿微細點陣網格紋理（dot-grid）",
    "primary": "#FFFFFF",
    "primary_use": "所有標題、強調文字",
    "secondary": "#666666",
    "secondary_use": "半透明容器背景、次要元素",
    "accent": "#FF6B35",
    "accent_use": "強調標籤、邊框、圖表重點",
    "support_hexes": [
      "#89CFF0",
      "#66BB6A"
    ],
    "typography_heading": "思源黑體（Noto Sans TC） heavy/900（取角色範圍上緣，巨大高對比，明顯大於其他文字，純白 #FFFFFF）",
    "typography_body": "Noto Sans TC regular–medium/400–500（取角色範圍下緣，寬鬆行距，白色或淺灰）",
    "illustration_default": "線條圖示",
    "mood": [
      "科技感強烈",
      "高對比黑白",
      "電路板美學",
      "發光線條"
    ],
    "deco_names": [
      "circuit-lines",
      "dot-grid-bg",
      "white-outline-rect",
      "separator-line",
      "orange-capsule-label",
      "numbered-circle",
      "glow-effect",
      "title-container-box"
    ],
    "closing": "Maintain strict two-tone discipline: pure white text and orange (#FF6B35) accents on near-black. Circuit-line decorations inhabit the outer margin zones only, c",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/dark-circuit-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：暗黑電路板風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "dark-circuit",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/dark-circuit.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "ecosystem-civic",
    "display_name": "柔和環形網絡風",
    "background_color": "#F8F8F7",
    "background_style": "清爽白灰底搭配網絡節點、角色關係與社群行動標記，適合 ecosystem、advocacy、volunteer operations 類內容",
    "primary": "#253646",
    "primary_use": "主標、中心結構、關鍵 network elements",
    "secondary": "#6B7686",
    "secondary_use": "補充說明、caption、次層 metadata",
    "accent": "#2C8B7A",
    "accent_use": "growth、coverage、community signal、relationship cue",
    "support_hexes": [
      "#DCE9E6",
      "#E8DDD2"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，帶 network / systems 感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 stakeholder、ops、signal、impact notes）",
    "illustration_default": "線條圖示",
    "mood": [
      "系統感",
      "柔和網絡",
      "環形節點",
      "可信"
    ],
    "deco_names": [
      "network-ring",
      "signal-bar",
      "role-badge",
      "leverage-callout"
    ],
    "closing": "The slide should feel like a coordinated soft network. Rings, signal bars, role badges, and pale structure should make relationships easy to scan before decorat",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/ecosystem-civic-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：柔和環形網絡風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "ecosystem-civic",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/ecosystem-civic.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "enablement-operations",
    "display_name": "灰藍工具框架風",
    "background_color": "#F7F8FA",
    "background_style": "清晰淺底搭配節奏帶、工具卡與 readiness 標記，適合 implementation、education 與 enablement 類執行內容",
    "primary": "#243142",
    "primary_use": "主標、主要框線、核心啟用資訊",
    "secondary": "#6E7A89",
    "secondary_use": "補充說明、caption、次層 metadata",
    "accent": "#4B7BEC",
    "accent_use": "readiness、phase highlight、activation cue",
    "support_hexes": [
      "#DDE6F8",
      "#EEDAC8"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，穩定俐落的 operations 感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合說明 steps、resources、checkpoints）",
    "illustration_default": "線條圖示",
    "mood": [
      "執行感",
      "清楚",
      "工具化",
      "灰藍框架"
    ],
    "deco_names": [
      "rollout-band",
      "checkpoint-dot",
      "toolkit-frame",
      "activation-arrow"
    ],
    "closing": "The slide should feel practical and tool-like. Rollout bands, checkpoint dots, and compact frame elements should create a clear operating rhythm without topic-s",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/enablement-operations-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：灰藍工具框架風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "enablement-operations",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/enablement-operations.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "executive-analytics",
    "display_name": "冷灰資料格線風",
    "background_color": "#F7F9FC",
    "background_style": "乾淨淺色底，帶細緻格線或極淡分區底塊，像企業分析報告或 QBR deck",
    "primary": "#1F2A44",
    "primary_use": "主標、主要數據、結構線",
    "secondary": "#6B7A90",
    "secondary_use": "次要文字、圖說、輔助標線",
    "accent": "#2F80ED",
    "accent_use": "關鍵圖表、KPI 強調、選中狀態",
    "support_hexes": [
      "#27AE60",
      "#EB5757",
      "#DCE6F5"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段偏上，企業報告感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合表格、數據與洞察說明）",
    "illustration_default": "無",
    "mood": [
      "理性",
      "乾淨",
      "冷灰格線",
      "資料節奏"
    ],
    "deco_names": [
      "gridline-background",
      "section-band",
      "chart-frame",
      "delta-pill"
    ],
    "closing": "The slide should feel crisp and data-forward: gridline backgrounds, section bands, and chart-like frames should support scanning while decoration remains unders",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/executive-analytics-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：冷灰資料格線風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "executive-analytics",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/executive-analytics.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "facilitation-learning",
    "display_name": "友善便利貼面板風",
    "background_color": "#F7F6F2",
    "background_style": "柔和淺色底，帶清楚的分區與教學節奏感，適合教學、工作坊與 onboarding",
    "primary": "#24405C",
    "primary_use": "主標、模組標題、結構線",
    "secondary": "#6D7788",
    "secondary_use": "補充文字、說明、材料註記",
    "accent": "#4F8F72",
    "accent_use": "checkpoint、重點強調、正向進展",
    "support_hexes": [
      "#DDE8F0",
      "#E8E1D2"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，友善但有秩序）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合說明文字與短標籤）",
    "illustration_default": "扁平插畫",
    "mood": [
      "友善",
      "清楚",
      "便利貼面板",
      "可執行"
    ],
    "deco_names": [
      "session-band",
      "checkpoint-marker",
      "toolkit-panel"
    ],
    "closing": "The slide should feel welcoming, clear, and practical. Soft session bands, checkpoint markers, and toolkit panels should reduce visual overwhelm and support for",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/facilitation-learning-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：友善便利貼面板風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "facilitation-learning",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/facilitation-learning.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "festive-patterned",
    "display_name": "亮色織紋圖騰風",
    "background_color": "#F7F1E8",
    "background_style": "奶油白底搭配黑色主塊與金砂色圖騰",
    "primary": "#1E1A17",
    "primary_use": "主標、深色橫帶",
    "secondary": "#B89B73",
    "secondary_use": "圖騰、邊框、細節",
    "accent": "#E3D4BF",
    "accent_use": "大面積背景與裝飾紙感",
    "support_hexes": [],
    "typography_heading": "展示字（粗體或窄體標題字） black/900（取角色範圍上緣，強化主視覺量體）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，讓內容不被裝飾吞沒）",
    "illustration_default": "抽象藝術",
    "mood": [
      "亮色",
      "圖騰感",
      "織紋節奏",
      "編排感強"
    ],
    "deco_names": [
      "woven-pattern",
      "black-band",
      "gold-frame"
    ],
    "closing": "Let the slide feel crafted and patterned. Woven motifs, black bands, and gold framing should build identity while typography remains clearly readable.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/festive-patterned-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：亮色織紋圖騰風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "festive-patterned",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/festive-patterned.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "grainy-editorial",
    "display_name": "顆粒紙面出版風",
    "background_color": "#F3EAE2",
    "background_style": "暖米白或棕灰紙底，帶細微 grain / print noise",
    "primary": "#2F2622",
    "primary_use": "主標題、正文",
    "secondary": "#8E776A",
    "secondary_use": "次要說明、細線、頁腳",
    "accent": "#B69078",
    "accent_use": "編號、細節裝飾、分隔線",
    "support_hexes": [
      "#D8C6B7"
    ],
    "typography_heading": "Noto Serif TC（高對比襯線展示字） bold/700（取角色範圍上緣，出版封面感）",
    "typography_body": "Noto Serif TC 或 Noto Sans TC regular/400（取角色範圍下緣，留白寬鬆）",
    "illustration_default": "無",
    "mood": [
      "安靜",
      "出版感",
      "紙張質地",
      "穩定"
    ],
    "deco_names": [
      "grain-noise",
      "hairline-rule",
      "corner-loop"
    ],
    "closing": "Keep the slide restrained and editorial. Texture should come from paper grain, hairline rules, and proportion, not from loud graphics.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/grainy-editorial-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：顆粒紙面出版風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "grainy-editorial",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/grainy-editorial.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "impact-report",
    "display_name": "柔和證據框架風",
    "background_color": "#F6F4EF",
    "background_style": "溫和淺底，兼具證據感與敘事節奏，適合摘要、對照與重點框架",
    "primary": "#243042",
    "primary_use": "主標、主要結論、重點數據",
    "secondary": "#6B7280",
    "secondary_use": "補充說明、方法註記、輔助圖說",
    "accent": "#B86B3E",
    "accent_use": "關鍵訊號、引言標記、亮點強調",
    "support_hexes": [
      "#D8E2EC",
      "#E7D9CF"
    ],
    "typography_heading": "Noto Sans TC（或低調高對比展示字） bold/700（取角色範圍中段，穩定報告型）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 findings、proof 與 recap 敘事）",
    "illustration_default": "無",
    "mood": [
      "可信",
      "溫和",
      "柔和框架",
      "證據感"
    ],
    "deco_names": [
      "highlight-ribbon",
      "quote-mark",
      "proof-frame"
    ],
    "closing": "The slide should feel calm, credible, and proof-oriented. Highlight ribbons, quote marks, and proof frames should make evidence feel visible without becoming vi",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/impact-report-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：柔和證據框架風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "impact-report",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/impact-report.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "lavender-media-kit",
    "display_name": "淡紫柔光資料包風",
    "background_color": "#F8F5F9",
    "background_style": "奶白底，淡紫與柔霧光暈點綴，中心構圖常見",
    "primary": "#5C4F8A",
    "primary_use": "主標與品牌名稱",
    "secondary": "#8C84B6",
    "secondary_use": "細線、說明與補充",
    "accent": "#B9A7E8",
    "accent_use": "柔光、標題襯底、模組頭",
    "support_hexes": [
      "#E8E0F5"
    ],
    "typography_heading": "Noto Serif TC（優雅襯線）或品牌展示字 medium–bold/500–700（取角色範圍中段偏上，中心構圖時可放大）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，保持專業乾淨）",
    "illustration_default": "無",
    "mood": [
      "精緻",
      "淡紫柔光",
      "軟奢",
      "中央規則"
    ],
    "deco_names": [
      "soft-glow",
      "central-rule",
      "lilac-strip"
    ],
    "closing": "The page should feel poised and airy: soft lavender glow, refined spacing, and centered typographic confidence should create a polished information surface.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/lavender-media-kit-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：淡紫柔光資料包風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "lavender-media-kit",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/lavender-media-kit.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "learning-community",
    "display_name": "層級徽章群組風",
    "background_color": "#F8F8F5",
    "background_style": "清亮中性底搭配成長節奏、badge 與社群互動感模組，適合 certification 與 community learning 類內容",
    "primary": "#253345",
    "primary_use": "主標、主要框線、核心學習結構",
    "secondary": "#6D7786",
    "secondary_use": "補充說明、次層文字、metadata",
    "accent": "#6A5AE0",
    "accent_use": "badge、level、community cue、growth signal",
    "support_hexes": [
      "#E3E0F6",
      "#DDEAD9"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，穩定又稍有親和力）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 progression、requirements、community notes）",
    "illustration_default": "扁平插畫",
    "mood": [
      "成長感",
      "徽章群組",
      "層級帶狀",
      "清楚"
    ],
    "deco_names": [
      "level-band",
      "badge-cluster",
      "loop-arrow",
      "prompt-card"
    ],
    "closing": "The slide should feel structured and welcoming. Level bands, badge clusters, and loop arrows should create a visible progression system without naming a specifi",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/learning-community-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：層級徽章群組風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "learning-community",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/learning-community.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "mission-governance",
    "display_name": "深綠徽章秩序風",
    "background_color": "#F7F3EC",
    "background_style": "溫潤淺底搭配細緻分隔線、治理結構框與信任感 metadata，適合 mission、stewardship、governance 類內容",
    "primary": "#21313D",
    "primary_use": "主標、治理主架構、關鍵 oversight structure",
    "secondary": "#6C726E",
    "secondary_use": "補充敘述、caption、次層說明",
    "accent": "#9A6A2A",
    "accent_use": "stewardship、value moment、approval cue、重點標記",
    "support_hexes": [
      "#D8D0C4",
      "#DCE5E2"
    ],
    "typography_heading": "Noto Serif TC（或半襯線） medium–bold/500–700（取角色範圍中段，穩定正式，帶 institutional gravitas）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 role、policy、journey note 與 stewardship 說明）",
    "illustration_default": "無",
    "mood": [
      "穩重",
      "值得信任",
      "深綠徽章",
      "人本秩序"
    ],
    "deco_names": [
      "governance-rule",
      "stewardship-chip",
      "oversight-frame",
      "trust-accent"
    ],
    "closing": "The slide should feel credible, orderly, and human. Rule lines, stewardship chips, and oversight frames should create trust through structure rather than heavy ",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/mission-governance-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：深綠徽章秩序風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "mission-governance",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/mission-governance.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "monochrome-editorial",
    "display_name": "單色材質編輯風",
    "background_color": "#E8E8E6",
    "background_style": "霧面灰階底搭配明暗材質研究與乾淨編輯界面，以比例、光影與字體對比建立層次",
    "primary": "#111111",
    "primary_use": "主標、主要文字與高對比細線",
    "secondary": "#4A4A48",
    "secondary_use": "次要文字、caption 與低層級資訊",
    "accent": "#FFFFFF",
    "accent_use": "反白區域、亮面留白與局部高光",
    "support_hexes": [
      "#B9B9B6",
      "#E8E8E6"
    ],
    "typography_heading": "Bodoni Moda / Noto Serif TC medium/500（取角色範圍上緣，使用高對比襯線形成編輯張力）",
    "typography_body": "Helvetica Neue / Noto Sans TC regular/400（取角色範圍下緣，保持精緻與克制）",
    "illustration_default": "無",
    "mood": [
      "克制",
      "高對比",
      "編輯感",
      "材質光影"
    ],
    "deco_names": [
      "material-shadow-field",
      "hairline-rule",
      "tonal-paper-layer"
    ],
    "closing": "Build sophistication through monochrome proportion, high-contrast serif typography, and abstract material light. Keep decoration sparse and separate from the ch",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "layout-style-cases/chapter-number-bg-left-title-rule.editorial-classic.webp",
    "preview_label": "YAML配對：章節數字背景左標：紙本編輯風",
    "preview_source": "style-case",
    "preview_match_score": 245,
    "preview_source_theme": "monochrome-editorial",
    "preview_yaml_path": "prompt_system/style_cases/chapter-number-bg-left-title-rule.editorial-classic.yaml",
    "preview_match_method": "yaml-palette"
  },
  {
    "id": "neo-brutalist-blocks",
    "display_name": "高彩新粗獷色塊風",
    "background_color": "#E9FF3F",
    "background_style": "高彩平面底搭配少量影印顆粒、硬邊輪廓與刻意錯位，整體直接、響亮且帶手工誤差",
    "primary": "#111111",
    "primary_use": "主文字、粗輪廓、陰影與結構記號",
    "secondary": "#1738FF",
    "secondary_use": "大型對比色塊與主要視覺面",
    "accent": "#FF4FB3",
    "accent_use": "次要色塊、貼紙感標記與局部碰撞",
    "support_hexes": [
      "#FFFFFF",
      "#E9FF3F"
    ],
    "typography_heading": "Space Grotesk / Noto Sans TC black/900（取角色範圍上緣，緊湊而強勢）",
    "typography_body": "Arial / Noto Sans TC bold/700（取角色範圍中段，保持短句的直接性）",
    "illustration_default": "幾何抽象",
    "mood": [
      "響亮",
      "粗獷",
      "平面碰撞",
      "刻意錯位"
    ],
    "deco_names": [
      "offset-block",
      "misregistered-shadow",
      "zigzag-mark",
      "photocopy-speckle"
    ],
    "closing": "Keep the visual language flat, high-contrast, and deliberately imperfect. Hard edges, offset shadows, and sparse print noise should create energy without determ",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme"
  },
  {
    "id": "operating-review",
    "display_name": "灰藍檢核線框風",
    "background_color": "#F6F7F9",
    "background_style": "乾淨白灰底搭配紀律感模組、健康訊號色與 review rhythm 條帶，適合 QBR / EBR / pipeline review",
    "primary": "#1D2736",
    "primary_use": "主標、主要框線、關鍵 review 結論",
    "secondary": "#6A768B",
    "secondary_use": "副標、補充說明、次要數據與標註",
    "accent": "#2E7D6A",
    "accent_use": "健康訊號、正向進展、commitment cue",
    "support_hexes": [
      "#DCE6F2",
      "#F2D6C6"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，穩定有秩序的 executive review 感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 KPI、owner、risk note、next step）",
    "illustration_default": "無",
    "mood": [
      "紀律",
      "清楚",
      "灰藍檢核",
      "線框節奏"
    ],
    "deco_names": [
      "review-band",
      "health-chip",
      "risk-flag",
      "owner-tag"
    ],
    "closing": "The slide should feel disciplined, time-aware, and easy to scan. Review bands, health chips, and risk flags should organize information with a restrained gray-b",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/operating-review-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：灰藍檢核線框風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "operating-review",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/operating-review.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "paper-collage-vintage",
    "display_name": "復古紙本拼貼風",
    "background_color": "#E7D2C7",
    "background_style": "粉棕紙底，重疊便條、撕紙邊與膠帶拼貼",
    "primary": "#3E2723",
    "primary_use": "主標題、主要文字與高對比拼貼標籤",
    "secondary": "#6D4C41",
    "secondary_use": "內文、線條與紙張陰影",
    "accent": "#C8A99B",
    "accent_use": "膠帶、便條、圓貼紙",
    "support_hexes": [
      "#D9C0B3"
    ],
    "typography_heading": "Noto Serif TC（柔和襯線）或海報感展示字 bold/700（取角色範圍中段偏上，agency 故事頁氣質）",
    "typography_body": "紙本感無襯線或打字機字（monospace 感） regular/400（取角色範圍中段）",
    "illustration_default": "抽象藝術",
    "mood": [
      "懷舊",
      "手作",
      "拼貼",
      "紙張層次"
    ],
    "deco_names": [
      "torn-edge",
      "tape-sticker",
      "layered-paper"
    ],
    "closing": "The slide should feel assembled by hand from paper scraps and notes. Texture and layering are the identity, but content hierarchy must stay legible.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/paper-collage-vintage-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：復古紙本拼貼風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "paper-collage-vintage",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/paper-collage-vintage.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "product-strategy-signal",
    "display_name": "現代訊號軸線風",
    "background_color": "#F5F7FA",
    "background_style": "乾淨淺色底搭配高對比訊號色，模組框線與定位標記清楚可掃描",
    "primary": "#18212F",
    "primary_use": "主標、主要框線、核心定位資訊",
    "secondary": "#5E6C82",
    "secondary_use": "副標、說明、次要結構文字",
    "accent": "#2D7FF9",
    "accent_use": "位置標記、關鍵進展、主要訊號",
    "support_hexes": [
      "#F08A24",
      "#DCE6F4"
    ],
    "typography_heading": "Noto Sans TC bold/700–800（取角色範圍中段偏上，product / pitch deck 的清晰速度感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合短條列、比較說明與 execution notes）",
    "illustration_default": "線條圖示",
    "mood": [
      "清楚",
      "策略化",
      "現代軸線",
      "訊號節點"
    ],
    "deco_names": [
      "axis-rule",
      "signal-dot",
      "motion-band",
      "directional-arrow"
    ],
    "closing": "The slide should feel strategic, readable, and directional. Axis rules, signal dots, and compact road markers should guide attention through the composition wit",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/product-strategy-signal-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：現代訊號軸線風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "product-strategy-signal",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/product-strategy-signal.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "quiet-enso",
    "display_name": "和紙留白手勢風",
    "background_color": "#F6F0E4",
    "background_style": "溫暖淺色紙面、細緻纖維與大片留白，以單一不完美手勢建立安靜張力",
    "primary": "#20201E",
    "primary_use": "主標、主要文字與深色結構",
    "secondary": "#55514A",
    "secondary_use": "次要文字、metadata 與低對比說明",
    "accent": "#D94838",
    "accent_use": "單一手勢、微小印記與有限重點",
    "support_hexes": [
      "#F6F0E4",
      "#D8CDB9"
    ],
    "typography_heading": "Cormorant Garamond / Noto Serif TC medium/500（取角色範圍中段偏上，字距舒展）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍下緣，維持安靜而清楚）",
    "illustration_default": "無",
    "mood": [
      "安靜",
      "留白",
      "紙張觸感",
      "單一手勢"
    ],
    "deco_names": [
      "dry-brush-ring",
      "seal-square",
      "paper-fiber"
    ],
    "closing": "Use material warmth, generous silence, and one imperfect gesture to create presence. The visual treatment should remain restrained and independent from any spec",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme"
  },
  {
    "id": "sales-conversion",
    "display_name": "深色金框條帶風",
    "background_color": "#FAFAF8",
    "background_style": "乾淨高對比商務底，搭配明確方案框、價值標記與成交導向的強調帶",
    "primary": "#18222F",
    "primary_use": "主標、主要框線、核心比較內容",
    "secondary": "#667287",
    "secondary_use": "補充說明、caption、次層資訊",
    "accent": "#1E8E5A",
    "accent_use": "ROI、推薦方案、正向成交訊號",
    "support_hexes": [
      "#E8EEF5",
      "#F2DFC8"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段偏上，清楚有力的 proposal 感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合 feature scan、ROI、objection notes）",
    "illustration_default": "線條圖示",
    "mood": [
      "可信",
      "深色條帶",
      "金色框線",
      "明確"
    ],
    "deco_names": [
      "offer-frame",
      "roi-badge",
      "proof-strip",
      "commitment-ribbon"
    ],
    "closing": "The slide should feel sharp and easy to scan. Offer frames, ROI badges, and proof strips should appear as visual devices, while decoration stays secondary to hi",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/sales-conversion-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：深色金框條帶風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "sales-conversion",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/sales-conversion.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "soft-organic-education",
    "display_name": "柔和有機泡形風",
    "background_color": "#F7F3EC",
    "background_style": "象牙白底，搭配低彩度有機圓角色塊",
    "primary": "#2C3A3F",
    "primary_use": "標題與正文",
    "secondary": "#8C9688",
    "secondary_use": "次文字與邊界輔助",
    "accent": "#C7B19E",
    "accent_use": "圓角裝飾塊、標記",
    "support_hexes": [
      "#B5C2BC",
      "#E2CEC0"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段偏上，厚實友善而現代）",
    "typography_body": "Noto Sans TC regular–medium/400–500（取角色範圍中段，適合教學資訊密度）",
    "illustration_default": "扁平插畫",
    "mood": [
      "友善",
      "柔和",
      "有機泡形",
      "有秩序"
    ],
    "deco_names": [
      "organic-blobs",
      "micro-grid",
      "rounded-panels"
    ],
    "closing": "Keep the presentation soft, approachable, and orderly. Organic blobs, rounded panels, and gentle grid cues should support pacing without dominating the structur",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/soft-organic-education-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：柔和有機泡形風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "soft-organic-education",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/soft-organic-education.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "strategy-consulting",
    "display_name": "酒紅理性格線風",
    "background_color": "#F8F8F6",
    "background_style": "乾淨白底或極淡灰底，搭配強結構框線、細分隔與清楚的優先層級",
    "primary": "#202632",
    "primary_use": "主標、主結構線、關鍵結論",
    "secondary": "#697385",
    "secondary_use": "補充說明、次層文字、輔助分隔",
    "accent": "#C96E3D",
    "accent_use": "建議、橋接、重點標示",
    "support_hexes": [
      "#E6DDD3",
      "#C7D7E8"
    ],
    "typography_heading": "Noto Sans TC bold/700（取角色範圍中段，克制但有力，executive summary 感）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，適合條列、分析與建議摘要）",
    "illustration_default": "無",
    "mood": [
      "理性",
      "清楚",
      "酒紅格線",
      "決策感"
    ],
    "deco_names": [
      "structural-rule",
      "focus-band",
      "recommendation-tag",
      "bridge-arrow"
    ],
    "closing": "The slide should feel analytical, selective, and purposeful. Recommendation stacks, burgundy rules, and clear proof frames should support argument clarity rathe",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/strategy-consulting-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：酒紅理性格線風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "strategy-consulting",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/strategy-consulting.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "teal-tech",
    "display_name": "靛藍端點科技風",
    "background_color": "#E8E8E8",
    "background_style": "淺灰或白色主背景，搭配靛藍綠標題色塊；深色版本用深靛藍（章節過場用）",
    "primary": "#4B8B99",
    "primary_use": "章節標題背景、重點框、主視覺區域（主導元素）",
    "secondary": "#76A5AF",
    "secondary_use": "框線、邊界元素、輔助圖形、散點",
    "accent": "#0FC1C3",
    "accent_use": "科技介面元素、特殊強調亮點",
    "support_hexes": [
      "#F3B76F",
      "#70C870"
    ],
    "typography_heading": "Noto Sans TC bold–black/700–900（取角色範圍上緣，幾何感強的章節標題，深靛藍 #1A3A42 或白色）",
    "typography_body": "Noto Sans TC regular–medium/400–500（取角色範圍中段，白色背景文字框內清晰呈現，深灰 #333333）",
    "illustration_default": "扁平插畫",
    "mood": [
      "科技現代",
      "親切友善",
      "靛藍端點",
      "有條理"
    ],
    "deco_names": [
      "circuit-endpoints",
      "scattered-dots",
      "dark-title-block",
      "content-outline-box",
      "bright-highlight-box",
      "numbered-badge",
      "flat-illustration",
      "arrow-flow"
    ],
    "closing": "Teal-blue (#4B8B99) defines structure and decoration. Circuit endpoint marks, scattered dots, and warm support accents should balance technical precision with a",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/teal-tech-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：靛藍端點科技風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "teal-tech",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/teal-tech.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "tech-navy",
    "display_name": "深藍青色線框風",
    "background_color": "#0B1220",
    "background_style": "深藍色背景，全頁疊一層極淡的細格線紋理（几乎看不見，只是質感）",
    "primary": "#F5F7FA",
    "primary_use": "標題、主要文字",
    "secondary": "#9AA7B8",
    "secondary_use": "副標、說明文字、次要資訊",
    "accent": "#3FD0E8",
    "accent_use": "強調線條、編號、圖示描邊、細節重點",
    "support_hexes": [
      "#1B2A3D"
    ],
    "typography_heading": "Noto Sans TC bold–black/700–900（取角色範圍上緣，標題須明顯大於其他文字，高對比白）",
    "typography_body": "Noto Sans TC regular–medium/400–500（取角色範圍下緣，寬鬆行距，灰藍色）",
    "illustration_default": "線條圖示",
    "mood": [
      "沉穩",
      "專業",
      "科技感",
      "冷色線框",
      "低調有序"
    ],
    "deco_names": [
      "hairline-divider",
      "corner-bracket",
      "grid-bg",
      "icon-badge",
      "mono-label-caption"
    ],
    "closing": "Maintain strict dark-navy-plus-single-cyan-accent discipline: the accent only marks lines, icon strokes, and small numerals. Decoration lives in the outer margi",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/tech-navy-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：深藍青色線框風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "tech-navy",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/tech-navy.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "warm-editorial-portfolio",
    "display_name": "暖調編輯紙面風",
    "background_color": "#F5EEE7",
    "background_style": "暖白或淡奶茶底，搭配 grainy photo overlay 與大幅留白",
    "primary": "#2A2521",
    "primary_use": "主標與關鍵文字",
    "secondary": "#8E7A6A",
    "secondary_use": "補充文字、細線、圖說",
    "accent": "#C3A58D",
    "accent_use": "底片框、邊線、標籤",
    "support_hexes": [
      "#D8C6B8"
    ],
    "typography_heading": "Noto Serif TC（editorial serif）或高對比展示字 bold/700（取角色範圍中段偏上，雜誌跨頁感）",
    "typography_body": "Noto Sans TC 或輕襯線 regular/400（取角色範圍下緣，乾淨細緻）",
    "illustration_default": "無",
    "mood": [
      "溫暖",
      "編輯感",
      "紙面質地",
      "安靜質感"
    ],
    "deco_names": [
      "grainy-photo-overlay",
      "caption-strip",
      "editorial-rule"
    ],
    "closing": "The page should feel like a warm editorial spread: image and type should cooperate as equals, with texture coming from grain, warm paper tone, and proportion.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/warm-editorial-portfolio-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：暖調編輯紙面風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "warm-editorial-portfolio",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/warm-editorial-portfolio.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "workshop-human",
    "display_name": "暖灰人本攝影風",
    "background_color": "#F4F2EE",
    "background_style": "灰白底，黑白攝影與粗字並置",
    "primary": "#2C2C2C",
    "primary_use": "主標與正文",
    "secondary": "#8D8B88",
    "secondary_use": "次標與框線",
    "accent": "#D98C8C",
    "accent_use": "情緒標記、工作坊小標",
    "support_hexes": [
      "#D8D3CC"
    ],
    "typography_heading": "Noto Sans TC bold/700–800（取角色範圍中段偏上，工作坊式節奏）",
    "typography_body": "Noto Sans TC regular/400（取角色範圍中段，清楚可讀）",
    "illustration_default": "無",
    "mood": [
      "人本",
      "暖灰",
      "攝影導向",
      "手作標記"
    ],
    "deco_names": [
      "monochrome-portrait",
      "workshop-label",
      "fine-divider"
    ],
    "closing": "Human warmth should come from photography-like texture and grounded spacing, not color overload. Keep the structure simple, tactile, and emotionally restrained.",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme",
    "preview_image": "theme-previews/workshop-human-cards-1-plus-3-codex.webp",
    "preview_label": "1+3 新圖：暖灰人本攝影風",
    "preview_source": "theme-preview-generated",
    "preview_match_score": 1000,
    "preview_source_theme": "workshop-human",
    "preview_yaml_path": "artifacts/generated-prompts/theme-previews/workshop-human.cards-1-plus-3.assembled.yaml",
    "preview_match_method": "generated-from-theme-yaml"
  },
  {
    "id": "y2k-chrome",
    "display_name": "千禧鏡面數位風",
    "background_color": "#D8D4FF",
    "background_style": "冰藍與薰衣草色的柔和數位漸層，搭配鏡面反射、半透明光暈與樂觀未來感",
    "primary": "#18235C",
    "primary_use": "主文字、深色結構與高可讀層級",
    "secondary": "#B8F7FF",
    "secondary_use": "冰藍高光、透明面與鏡面反射",
    "accent": "#FF70C9",
    "accent_use": "粉色光暈、鏡頭光與局部訊號",
    "support_hexes": [
      "#C7A6FF",
      "#F6FBFF"
    ],
    "typography_heading": "Arial Rounded / Noto Sans TC extra-bold/800（取角色範圍上緣，字面寬、輪廓圓潤）",
    "typography_body": "Inter / Noto Sans TC semi-bold/600（取角色範圍中段，清晰而具數位感）",
    "illustration_default": "3D 幾何抽象",
    "mood": [
      "樂觀未來",
      "鏡面",
      "數位光暈",
      "千禧復古"
    ],
    "deco_names": [
      "chrome-loop",
      "iridescent-gradient",
      "sparkle-mark",
      "lens-flare"
    ],
    "closing": "Reinterpret early-digital optimism with polished chrome, translucent light, and rounded typography. The visual vocabulary must remain reusable across layouts an",
    "theme_kind": "spec",
    "theme_kind_label": "規格 Theme"
  },
  {
    "id": "line-argument-journal",
    "display_name": "線性論證誌",
    "background_color": "#F5F4F0",
    "background_style": "黑體主張、證據分隔線與編輯式留白 · 冷白編輯紙、黑墨與酒紅校樣記號",
    "primary": "#17191A",
    "primary_use": "主要文字與結構",
    "secondary": "#8D3028",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#5D666D",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#C7C9C5",
      "#FFFFFF"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "公共議題編輯"
    ],
    "deco_names": [
      "證據分隔線",
      "論點編號",
      "校樣色標",
      "留白節奏"
    ],
    "closing": "像一份有立場的公共議題長文：靠句子、節奏、留白與結構說服，不靠卡片堆滿畫面。",
    "preview_image": "theme-presets/line-argument-journal.jpg",
    "preview_label": "HTML Preset · 12 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "line-argument-journal",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/line-argument-journal/",
    "topic_title": "晚歸不是個人問題：夜間照護服務提案",
    "slide_count": 12,
    "pattern": "黑體主張、證據分隔線與編輯式留白",
    "material": "冷白編輯紙、黑墨與酒紅校樣記號",
    "design_intent": "像一份有立場的公共議題長文：靠句子、節奏、留白與結構說服，不靠卡片堆滿畫面。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "signal-route-atlas",
    "display_name": "訊號軌道路線圖",
    "background_color": "#F2EFE5",
    "background_style": "72px 座標底格與逐頁變形的單一轉乘主線 · 暖霧地圖紙、平塗深藍油墨與訊號橘綠",
    "primary": "#102A36",
    "primary_use": "主要文字與結構",
    "secondary": "#D45A2F",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#1C7777",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#4E6269",
      "#FAF8F1"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "產品決策系統"
    ],
    "deco_names": [
      "轉乘主線",
      "描邊站點",
      "票券穿孔",
      "時刻表分隔"
    ],
    "closing": "像一套真正可操作的轉乘地圖系統；每頁的線、站點與票券都直接回答內容問題。",
    "preview_image": "theme-presets/signal-route-atlas.jpg",
    "preview_label": "HTML Preset · 12 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "signal-route-atlas",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/signal-route-atlas/",
    "topic_title": "把客服雜訊變成產品決策",
    "slide_count": 12,
    "pattern": "72px 座標底格與逐頁變形的單一轉乘主線",
    "material": "暖霧地圖紙、平塗深藍油墨與訊號橘綠",
    "design_intent": "像一套真正可操作的轉乘地圖系統；每頁的線、站點與票券都直接回答內容問題。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case",
      "reusable-preset"
    ]
  },
  {
    "id": "field-index-manual",
    "display_name": "田野索引手冊",
    "background_color": "#E9EEE8",
    "background_style": "索引碼、欄位分隔與手冊式資訊列 · 灰綠檔案紙、深綠油墨與酒紅校訂章",
    "primary": "#143D2D",
    "primary_use": "主要文字與結構",
    "secondary": "#87374B",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#D6B34A",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#27302B",
      "#FAFAF7"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "地方服務交接"
    ],
    "deco_names": [
      "章節索引碼",
      "欄位分隔線",
      "手冊頁標",
      "校訂色標"
    ],
    "closing": "像田野工作者真的會帶在身上的服務手冊；內容可查找、可交接，也保留人的語氣。",
    "preview_image": "theme-presets/field-index-manual.jpg",
    "preview_label": "HTML Preset · 12 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "field-index-manual",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/field-index-manual/",
    "topic_title": "市場熄燈前的數位交接",
    "slide_count": 12,
    "pattern": "索引碼、欄位分隔與手冊式資訊列",
    "material": "灰綠檔案紙、深綠油墨與酒紅校訂章",
    "design_intent": "像田野工作者真的會帶在身上的服務手冊；內容可查找、可交接，也保留人的語氣。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "tide-signal-observatory",
    "display_name": "潮汐訊號觀測站",
    "background_color": "#062C33",
    "background_style": "觀測列、基準卡與雙色狀態線 · 深海儀表板、霧面資訊面與航測標記",
    "primary": "#F2F1E8",
    "primary_use": "主要文字與結構",
    "secondary": "#246E79",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#B9432C",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#577A7B",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "海岸資料觀測"
    ],
    "deco_names": [
      "觀測分隔線",
      "潮位標記",
      "採樣編號",
      "決策黃標"
    ],
    "closing": "像一座真的在看海的觀測站：先看訊號從哪裡來，再看它何時值得介入。",
    "preview_image": "theme-presets/tide-signal-observatory.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "tide-signal-observatory",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/tide-signal-observatory/",
    "topic_title": "讓海岸自己說出變化",
    "slide_count": 10,
    "pattern": "觀測列、基準卡與雙色狀態線",
    "material": "深海儀表板、霧面資訊面與航測標記",
    "design_intent": "像一座真的在看海的觀測站：先看訊號從哪裡來，再看它何時值得介入。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "craft-archive-editions",
    "display_name": "手藝記憶編目誌",
    "background_color": "#EFE5D4",
    "background_style": "編目列、版次編號與手工校樣線 · 舊紙、深墨、硃砂章與裝訂線",
    "primary": "#2B2118",
    "primary_use": "主要文字與結構",
    "secondary": "#B33A2B",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#315E57",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#CDBDA8",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "文化技藝保存"
    ],
    "deco_names": [
      "編目分隔線",
      "版次編號",
      "硃紅校樣",
      "裝訂基準"
    ],
    "closing": "像一本正在被持續修訂的地方誌：保留人的語氣，也清楚標出哪些知識仍需驗證。",
    "preview_image": "theme-presets/craft-archive-editions.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "craft-archive-editions",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/craft-archive-editions/",
    "topic_title": "把一座城市的手藝，編成可以繼續讀的地方誌",
    "slide_count": 10,
    "pattern": "編目列、版次編號與手工校樣線",
    "material": "舊紙、深墨、硃砂章與裝訂線",
    "design_intent": "像一本正在被持續修訂的地方誌：保留人的語氣，也清楚標出哪些知識仍需驗證。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "incident-command-redline",
    "display_name": "資安戰情紅線",
    "background_color": "#111111",
    "background_style": "嚴重度標記、時間列與事件分隔線 · 黑色戰情板、霧面資訊牌與紅線標記",
    "primary": "#F4F1EA",
    "primary_use": "主要文字與結構",
    "secondary": "#FF4A3D",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#F4C84C",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#AAA59C",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "事件指揮與復原"
    ],
    "deco_names": [
      "嚴重度色標",
      "事件分隔線",
      "事件時間碼",
      "紅線優先級"
    ],
    "closing": "像一間真的在運作的事件指揮室：先建立事實，再控制影響，最後留下能復原的決策紀錄。",
    "preview_image": "theme-presets/incident-command-redline.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "incident-command-redline",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/incident-command-redline/",
    "topic_title": "在 17 分鐘內，看懂一次正在擴大的資安事件",
    "slide_count": 10,
    "pattern": "嚴重度標記、時間列與事件分隔線",
    "material": "黑色戰情板、霧面資訊牌與紅線標記",
    "design_intent": "像一間真的在運作的事件指揮室：先建立事實，再控制影響，最後留下能復原的決策紀錄。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "harbor-ribbon-program",
    "display_name": "港灣織帶節目冊",
    "background_color": "#FFF4D8",
    "background_style": "節目索引、雙色規則與海報式資訊格 · 絲網印刷紙、節目單與港區導覽色標",
    "primary": "#16325C",
    "primary_use": "主要文字與結構",
    "secondary": "#F45B69",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#168F8A",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#F4C84C",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "文化節慶策展"
    ],
    "deco_names": [
      "節目色標",
      "票券編號",
      "港區索引",
      "海報分隔線"
    ],
    "closing": "像一本會帶人走進港區的節目冊：熱鬧，但每一條色帶都對應真實內容與路線。",
    "preview_image": "theme-presets/harbor-ribbon-program.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "harbor-ribbon-program",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/harbor-ribbon-program/",
    "topic_title": "讓三天的港灣燈節，成為一整年的文化引擎",
    "slide_count": 10,
    "pattern": "節目索引、雙色規則與海報式資訊格",
    "material": "絲網印刷紙、節目單與港區導覽色標",
    "design_intent": "像一本會帶人走進港區的節目冊：熱鬧，但每一條色帶都對應真實內容與路線。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "neighborhood-newsroom-proof",
    "display_name": "街區新聞校樣紙",
    "background_color": "#F5F0E5",
    "background_style": "低對比新聞紙點陣、細欄線與極淡藍灰光暈 · 社區報紙、藍黑油墨與紅筆校樣",
    "primary": "#17202A",
    "primary_use": "主要文字與結構",
    "secondary": "#C93B32",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#27658A",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#65707A",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "社區資訊治理"
    ],
    "deco_names": [
      "新聞紙點陣 Pattern",
      "細欄線",
      "校樣色標",
      "證據編號"
    ],
    "closing": "像一份居民真的會翻、會圈、會更正的地方報紙；資訊來源與回應責任都看得見。",
    "preview_image": "theme-presets/neighborhood-newsroom-proof.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "neighborhood-newsroom-proof",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/neighborhood-newsroom-proof/",
    "topic_title": "一份只有八頁的社區報，如何重新連起三條街",
    "slide_count": 10,
    "pattern": "低對比新聞紙點陣、細欄線與極淡藍灰光暈",
    "material": "社區報紙、藍黑油墨與紅筆校樣",
    "design_intent": "像一份居民真的會翻、會圈、會更正的地方報紙；資訊來源與回應責任都看得見。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "scent-veil-launch",
    "display_name": "香氣薄霧發表誌",
    "background_color": "#F6F0F3",
    "background_style": "香調索引、細緻分隔與留白段落 · 細緻紙張、柔白資訊面與霧面香氛標籤",
    "primary": "#3B2338",
    "primary_use": "主要文字與結構",
    "secondary": "#A44A6D",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#C9907B",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#806C7B",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "品牌體驗設計"
    ],
    "deco_names": [
      "香調色標",
      "細緻分隔線",
      "氣味索引",
      "留白焦點"
    ],
    "closing": "像一次克制的香氣體驗：先讓人感受，再提供語言，最後留下可以被帶回生活的記憶。",
    "preview_image": "theme-presets/scent-veil-launch.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "scent-veil-launch",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/scent-veil-launch/",
    "topic_title": "把一支新香氣，設計成會被記住的品牌儀式",
    "slide_count": 10,
    "pattern": "香調索引、細緻分隔與留白段落",
    "material": "細緻紙張、柔白資訊面與霧面香氛標籤",
    "design_intent": "像一次克制的香氣體驗：先讓人感受，再提供語言，最後留下可以被帶回生活的記憶。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case",
      "reusable-preset"
    ]
  },
  {
    "id": "restoration-blueprint-ledger",
    "display_name": "老屋修復測繪簿",
    "background_color": "#E9E2D2",
    "background_style": "滿版泛黃測繪紙、連續上下細線與少量大型角落曲線 · 滿版泛黃藍圖紙、深藍墨線與銅色修訂筆",
    "primary": "#15334B",
    "primary_use": "主要文字與結構",
    "secondary": "#A94E20",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#386F73",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#6A716E",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "建築保存決策"
    ],
    "deco_names": [
      "可移動建築插圖",
      "上下連續細線",
      "大型角落曲線",
      "克制留白"
    ],
    "closing": "像一本真的會跟著工地更新的建築編輯誌：內容頁讓資訊與留白主導，封面與結尾才以單側裁切插圖形成視覺記憶。",
    "preview_image": "theme-presets/restoration-blueprint-ledger.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "restoration-blueprint-ledger",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/restoration-blueprint-ledger/",
    "topic_title": "修一棟老屋，不抹掉時間留下的痕跡",
    "slide_count": 10,
    "pattern": "滿版泛黃測繪紙、連續上下細線與少量大型角落曲線",
    "material": "滿版泛黃藍圖紙、深藍墨線與銅色修訂筆",
    "design_intent": "像一本真的會跟著工地更新的建築編輯誌：內容頁讓資訊與留白主導，封面與結尾才以單側裁切插圖形成視覺記憶。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "ai-operations-signal",
    "display_name": "AI 營運訊號軸",
    "background_color": "#101912",
    "background_style": "逐頁移位的藍綠 SVG 訊號 Glow、任務索引與操作分隔線 · 深色營運面板、酸綠狀態條與藍色交接線",
    "primary": "#F2F5E9",
    "primary_use": "主要文字與結構",
    "secondary": "#C8F169",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#59A7FF",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#9FB0A0",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "組織工作系統"
    ],
    "deco_names": [
      "SVG 訊號 Glow",
      "決策色標",
      "任務編號",
      "營運交接線"
    ],
    "closing": "像一套真正能管理 AI 工作的 operating system：每一步都知道輸入、責任、品質與停止條件。",
    "preview_image": "theme-presets/ai-operations-signal.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "ai-operations-signal",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/ai-operations-signal/",
    "topic_title": "九十天，讓 AI 助手真正進入團隊工作流",
    "slide_count": 10,
    "pattern": "逐頁移位的藍綠 SVG 訊號 Glow、任務索引與操作分隔線",
    "material": "深色營運面板、酸綠狀態條與藍色交接線",
    "design_intent": "像一套真正能管理 AI 工作的 operating system：每一步都知道輸入、責任、品質與停止條件。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case",
      "reusable-preset"
    ]
  },
  {
    "id": "brave-classroom-contours",
    "display_name": "勇敢教室等高線",
    "background_color": "#F7F1DE",
    "background_style": "低對比教具紙點陣、鼠尾草綠與珊瑚色柔和光暈 · 霧面教具紙、暖白資訊面與圓角學習卡",
    "primary": "#183E32",
    "primary_use": "主要文字與結構",
    "secondary": "#E36B4C",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#5E9F87",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#68786E",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "學習參與設計"
    ],
    "deco_names": [
      "教具紙點陣 Pattern",
      "參與色標",
      "回應分隔線",
      "低壓提示"
    ],
    "closing": "像一間允許不同速度靠近的教室：不把大聲回答當成唯一參與，也不讓安靜的人消失。",
    "preview_image": "theme-presets/brave-classroom-contours.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "brave-classroom-contours",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/brave-classroom-contours/",
    "topic_title": "讓害怕開口的孩子，也能參與一堂課",
    "slide_count": 10,
    "pattern": "低對比教具紙點陣、鼠尾草綠與珊瑚色柔和光暈",
    "material": "霧面教具紙、暖白資訊面與圓角學習卡",
    "design_intent": "像一間允許不同速度靠近的教室：不把大聲回答當成唯一參與，也不讓安靜的人消失。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "night-transit-wayfinding",
    "display_name": "夜行交通導視圖",
    "background_color": "#15181C",
    "background_style": "夜間節點、路徑索引與低對比導視線 · 深色站牌、反光琥珀標記與青色替代路線",
    "primary": "#F7F4E8",
    "primary_use": "主要文字與結構",
    "secondary": "#FFB33E",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#41C7D9",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#AEB3B8",
      "#F7F7F5"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML pattern、陰影與語意化結構，不依賴圖片式底圖",
    "mood": [
      "HTML Preset",
      "深夜移動韌性"
    ],
    "deco_names": [
      "路徑色標",
      "站點索引",
      "末班時間碼",
      "替代路徑標記"
    ],
    "closing": "像一張深夜真的看得懂的交通圖：每一條線都能走、每一個點都有人接、每一個中斷都有退路。",
    "preview_image": "theme-presets/night-transit-wayfinding.jpg",
    "preview_label": "HTML Preset · 10 頁",
    "preview_source": "html-theme-lab",
    "preview_match_score": 1000,
    "preview_source_theme": "night-transit-wayfinding",
    "preview_yaml_path": "prompt_system/demos/html-theme-lab-extensions.json",
    "preview_match_method": "authored-html-preset",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/night-transit-wayfinding/",
    "topic_title": "讓深夜後的回家路，不再只靠運氣",
    "slide_count": 10,
    "pattern": "夜間節點、路徑索引與低對比導視線",
    "material": "深色站牌、反光琥珀標記與青色替代路線",
    "design_intent": "像一張深夜真的看得懂的交通圖：每一條線都能走、每一個點都有人接、每一個中斷都有退路。",
    "preset_registry_status": "published",
    "preset_capabilities": [
      "theme-lab-case"
    ]
  },
  {
    "id": "sepia-retail-case",
    "display_name": "暖褐編輯報告",
    "background_color": "#f3ede3",
    "background_style": "左重暖褐編輯欄搭配寬留白，資訊沿紙面基準線與短章節標記展開",
    "primary": "#2d211b",
    "primary_use": "主要文字與結構",
    "secondary": "#6f5e54",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#a96938",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#d6b78f",
      "#fffaf2"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML Pattern、字體、陰影與語意化幾何",
    "mood": [
      "HTML Preset",
      "正式 Preset Catalog"
    ],
    "deco_names": [
      "paper-grain",
      "narrow-column-rule",
      "warm-matte-shadow",
      "solid-ink-type"
    ],
    "closing": "左重暖褐編輯欄搭配寬留白，資訊沿紙面基準線與短章節標記展開",
    "preview_image": "theme-presets/sepia-retail-case.jpg",
    "preview_label": "HTML Preset · 20 頁",
    "preview_source": "html-preset-catalog",
    "preview_match_score": 1000,
    "preview_source_theme": "sepia-retail-case",
    "preview_yaml_path": "",
    "preview_match_method": "curated-html-preset-catalog",
    "preview_source_path": "artifacts/theme-demos/html-theme-lab/qa/contact-sheets/sepia-retail-case/contact-01.jpg",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/sepia-retail-case/",
    "topic_title": "",
    "slide_count": 20,
    "pattern": "warm-editorial-field",
    "material": "paper-grain · narrow-column-rule · warm-matte-shadow · solid-ink-type",
    "design_intent": "左重暖褐編輯欄搭配寬留白，資訊沿紙面基準線與短章節標記展開",
    "base_theme": "grainy-editorial",
    "example_layouts": [],
    "preset_registry_status": "published",
    "preset_capabilities": [
      "reusable-preset"
    ]
  },
  {
    "id": "dark-ai-city",
    "display_name": "深色城市軌道",
    "background_color": "#0b1220",
    "background_style": "中央主張與城市軌道圓環互相配重，內容沿網格與稀疏節點形成視線路徑",
    "primary": "#f5f7fa",
    "primary_use": "主要文字與結構",
    "secondary": "#9aa7b8",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#3fd0e8",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#62d6a7",
      "#111d2c"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML Pattern、字體、陰影與語意化幾何",
    "mood": [
      "HTML Preset",
      "正式 Preset Catalog"
    ],
    "deco_names": [
      "orbit-rings",
      "coordinate-grid",
      "low-light-gradient",
      "solid-signal-type"
    ],
    "closing": "中央主張與城市軌道圓環互相配重，內容沿網格與稀疏節點形成視線路徑",
    "preview_image": "theme-presets/dark-ai-city.jpg",
    "preview_label": "HTML Preset · 8 頁",
    "preview_source": "html-preset-catalog",
    "preview_match_score": 1000,
    "preview_source_theme": "dark-ai-city",
    "preview_yaml_path": "",
    "preview_match_method": "curated-html-preset-catalog",
    "preview_source_path": "artifacts/theme-demos/html-theme-lab/qa/contact-sheets/dark-ai-city/contact-01.jpg",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/dark-ai-city/",
    "topic_title": "",
    "slide_count": 8,
    "pattern": "urban-orbit-system",
    "material": "orbit-rings · coordinate-grid · low-light-gradient · solid-signal-type",
    "design_intent": "中央主張與城市軌道圓環互相配重，內容沿網格與稀疏節點形成視線路徑",
    "base_theme": "dark-circuit",
    "example_layouts": [],
    "preset_registry_status": "published",
    "preset_capabilities": [
      "reusable-preset"
    ]
  },
  {
    "id": "dark-city-network-report",
    "display_name": "深色城市編輯",
    "background_color": "#091525",
    "background_style": "深色專題封面與資料新聞內容頁交替，版心用路網細線與內收陰影維持連續",
    "primary": "#ffffff",
    "primary_use": "主要文字與結構",
    "secondary": "#d9e2ee",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#75bfe8",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#d4af7e",
      "#10253a"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML Pattern、字體、陰影與語意化幾何",
    "mood": [
      "HTML Preset",
      "正式 Preset Catalog"
    ],
    "deco_names": [
      "city-network-lines",
      "diagonal-weave",
      "inset-shadow",
      "editorial-rule"
    ],
    "closing": "深色專題封面與資料新聞內容頁交替，版心用路網細線與內收陰影維持連續",
    "preview_image": "theme-presets/dark-city-network-report.jpg",
    "preview_label": "HTML Preset · 8 頁",
    "preview_source": "html-preset-catalog",
    "preview_match_score": 1000,
    "preview_source_theme": "dark-city-network-report",
    "preview_yaml_path": "",
    "preview_match_method": "curated-html-preset-catalog",
    "preview_source_path": "artifacts/theme-demos/html-theme-lab/qa/contact-sheets/dark-city-network-report/contact-01.jpg",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/dark-city-network-report/",
    "topic_title": "",
    "slide_count": 8,
    "pattern": "civic-network-editorial",
    "material": "city-network-lines · diagonal-weave · inset-shadow · editorial-rule",
    "design_intent": "深色專題封面與資料新聞內容頁交替，版心用路網細線與內收陰影維持連續",
    "base_theme": "brand-editorial",
    "example_layouts": [],
    "preset_registry_status": "published",
    "preset_capabilities": [
      "reusable-preset"
    ]
  },
  {
    "id": "clinical-evidence-atlas",
    "display_name": "臨床證據圖譜",
    "background_color": "#F5F8FA",
    "background_style": "白色與霧藍灰構成臨床證據頁面，青綠證據脊線串接病程、效益與成熟度，珊瑚紅只標示風險、限制與需回退的決策點",
    "primary": "#17343D",
    "primary_use": "主要文字與結構",
    "secondary": "#58707A",
    "secondary_use": "次要層級與輔助資訊",
    "accent": "#0B7A75",
    "accent_use": "狀態、重點與導引",
    "support_hexes": [
      "#D96C5F",
      "#FFFFFF"
    ],
    "typography_heading": "Noto Sans TC",
    "typography_body": "Noto Sans TC",
    "illustration_default": "純 HTML Pattern、字體、陰影與語意化幾何",
    "mood": [
      "HTML Preset",
      "正式 Preset Catalog"
    ],
    "deco_names": [
      "clinical-rule-grid",
      "evidence-spine",
      "risk-marker",
      "solid-ink-type"
    ],
    "closing": "白色與霧藍灰構成臨床證據頁面，青綠證據脊線串接病程、效益與成熟度，珊瑚紅只標示風險、限制與需回退的決策點",
    "preview_image": "theme-presets/clinical-evidence-atlas.jpg",
    "preview_label": "HTML Preset · 31 頁",
    "preview_source": "html-preset-catalog",
    "preview_match_score": 1000,
    "preview_source_theme": "clinical-evidence-atlas",
    "preview_yaml_path": "",
    "preview_match_method": "curated-html-preset-catalog",
    "preview_source_path": "artifacts/theme-demos/html-theme-lab/qa/contact-sheets/clinical-evidence-atlas/contact-01.jpg",
    "theme_kind": "html-preset",
    "theme_kind_label": "HTML Preset",
    "html_url": "/theme-html-lab/clinical-evidence-atlas/",
    "topic_title": "",
    "slide_count": 31,
    "pattern": "clinical-evidence-editorial",
    "material": "clinical-rule-grid · evidence-spine · risk-marker · solid-ink-type",
    "design_intent": "白色與霧藍灰構成臨床證據頁面，青綠證據脊線串接病程、效益與成熟度，珊瑚紅只標示風險、限制與需回退的決策點",
    "base_theme": "brand-editorial",
    "example_layouts": [],
    "preset_registry_status": "published",
    "preset_capabilities": [
      "reusable-preset"
    ]
  }
];
